[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:run_with_reloader:597:INFO] Watching for file changes with StatReloader
[/home/felix/Downloads/scalyr/mysite/myapp/views.py:home:10:ERROR] Something went wrong !!
[/home/felix/.local/lib/python3.5/site-packages/django/core/servers/basehttp.py:log_message:154:INFO] "GET / HTTP/1.1" 200 29
[/home/felix/.local/lib/python3.5/site-packages/django/core/servers/basehttp.py:log_message:154:INFO] "GET /test_server_error HTTP/1.1" 301 0
[/home/felix/.local/lib/python3.5/site-packages/django/utils/log.py:log_response:228:ERROR] Internal Server Error: /test_server_error/
[/home/felix/.local/lib/python3.5/site-packages/django/core/servers/basehttp.py:log_message:154:ERROR] "GET /test_server_error/ HTTP/1.1" 500 29
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:trigger_reload:217:INFO] /home/felix/Downloads/scalyr/mysite/myapp/views.py changed, reloading.
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:run_with_reloader:597:INFO] Watching for file changes with StatReloader
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:trigger_reload:217:INFO] /home/felix/Downloads/scalyr/mysite/mysite/urls.py changed, reloading.
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:run_with_reloader:597:INFO] Watching for file changes with StatReloader
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:trigger_reload:217:INFO] /home/felix/Downloads/scalyr/mysite/mysite/urls.py changed, reloading.
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:run_with_reloader:597:INFO] Watching for file changes with StatReloader
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:trigger_reload:217:INFO] /home/felix/Downloads/scalyr/mysite/mysite/urls.py changed, reloading.
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:run_with_reloader:597:INFO] Watching for file changes with StatReloader
[/home/felix/Downloads/scalyr/mysite/myapp/views.py:home:10:ERROR] Something went wrong !!
[/home/felix/.local/lib/python3.5/site-packages/django/core/servers/basehttp.py:log_message:154:INFO] "GET / HTTP/1.1" 200 29
[/home/felix/.local/lib/python3.5/site-packages/django/core/servers/basehttp.py:log_message:154:INFO] "GET /log_server_error HTTP/1.1" 301 0
[/home/felix/.local/lib/python3.5/site-packages/django/utils/log.py:log_response:228:ERROR] Internal Server Error: /log_server_error/
[/home/felix/.local/lib/python3.5/site-packages/django/core/servers/basehttp.py:log_message:154:ERROR] "GET /log_server_error/ HTTP/1.1" 500 29
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:trigger_reload:217:INFO] /home/felix/Downloads/scalyr/mysite/myapp/views.py changed, reloading.
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:run_with_reloader:597:INFO] Watching for file changes with StatReloader
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:trigger_reload:217:INFO] /home/felix/Downloads/scalyr/mysite/myapp/views.py changed, reloading.
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:run_with_reloader:597:INFO] Watching for file changes with StatReloader
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:trigger_reload:217:INFO] /home/felix/Downloads/scalyr/mysite/myapp/views.py changed, reloading.
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:run_with_reloader:597:INFO] Watching for file changes with StatReloader
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:trigger_reload:217:INFO] /home/felix/Downloads/scalyr/mysite/myapp/views.py changed, reloading.
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:run_with_reloader:597:INFO] Watching for file changes with StatReloader
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:trigger_reload:217:INFO] /home/felix/Downloads/scalyr/mysite/myapp/views.py changed, reloading.
[/home/felix/.local/lib/python3.5/site-packages/django/utils/autoreload.py:run_with_reloader:597:INFO] Watching for file changes with StatReloader
[/home/felix/.local/lib/python3.5/site-packages/django/utils/log.py:log_response:228:ERROR] Internal Server Error: /log_server_error/
[/home/felix/.local/lib/python3.5/site-packages/django/core/servers/basehttp.py:log_message:154:ERROR] "GET /log_server_error/ HTTP/1.1" 500 26
[/home/felix/.local/lib/python3.5/site-packages/django/utils/log.py:log_response:228:WARNING] Not Found: /l
[/home/felix/.local/lib/python3.5/site-packages/django/core/servers/basehttp.py:log_message:154:WARNING] "GET /l HTTP/1.1" 404 2197
[/home/felix/Downloads/scalyr/mysite/myapp/views.py:home:10:ERROR] Something went wrong !!
[/home/felix/.local/lib/python3.5/site-packages/django/core/servers/basehttp.py:log_message:154:INFO] "GET / HTTP/1.1" 200 29
